### ISSUE TITLE
How to use pre-trained model

### ISSUE THREAD

**Issue by MingtaoGuo** [clovaai/lffont#15]
Hi,

Thank you for your fantastic work! It's very helpful.

But when I execute the 'evaluator.py', there are some problems.

1. I use the command directly:

python evaluator.py \
    cfgs/factorize.yaml \
    --weight weight/generator.pth \
    --img_dir path/to/save/images \
    --test_meta meta/test.json

error output: lmdb.Error: /path/to/lmdb: No such file or directory

Best regards
GMT

**Comment by SanghyukChun** [comment]
@MingtaoGuo 
Thanks for your question.
#2 is a very related issue to your question. Could you follow #2?

**Comment by MingtaoGuo** [comment]
Thanks for your reply so quickly !!! very thank you!

I see the related issue, however, it still didn't work.

""'
If I want to test pretrained weight, :

1. I should write test.json first
2. then make the lmdb file for test.json
3. modify the data_path and data_meta in cfgs/defaults.yaml
""'

Firstly, I download the .ttf file, and make the json file, then execute the build_dataset.py, it's ok. 
the above step can generate a json file, like this:
{"font1": ["6625", "590F", "79CB", "51AC"]}

but when I run evaluator.py, the error output is "lmdb.Error: ./path/to/lmbd: No such file or directory". Maybe, I should modify data_path and data_meta in cfgs/defaults.yaml, but I don't know what means of these two parameters. could 
you tell me how to fix this problem?

thank you very much!

GMT

**Comment by SanghyukChun** [comment]
@MingtaoGuo 
For efficiency, we use the dataset as LMDB format, which is a self-contained database format, instead of raw images.
We do not provide the pre-extracted LMDB in our repository, but you have to build the dataset by yourself.

Could you follow the following instruction?
https://github.com/clovaai/lffont#prepare-datasets

After building your own LMDB, please change the paths in the example configuration file.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming my answer resolves the problem.
Please re-open the issue as necessary.
