### ISSUE TITLE
when evaluator phase1,it occurs a error named "TypeError: __init__() missing 1 required positional argument: 'emb_block"

### ISSUE THREAD

**Issue by clscy** [clovaai/lffont#16]
Hi, when evaluator phase1, it occurs a error "TypeError: __init__() missing 1 required positional argument: 'emb_block"。what wrong with it? Thank you.

**Comment by 8uos** [comment]
Sorry for missing some arguments in README and evaluator.
I updated the README and evaluator.py file. Please check it first.

For the error,
Did you modified the "cfgs/defaults.yaml" file or removed the 'default' argument in this ([line](https://github.com/clovaai/lffont/blob/48b7fe27363e97abba73f2b6855ec2877fb80785/evaluator.py#L126))?
I do not recommend modifying the "cfgs/defaults.yaml" file directly, because the arguments defined in that file are required to build the model, even if it is blank.
You can overwrite by defining the argument in the command line (like --data_path in [here](https://github.com/clovaai/lffont#test)). 

Also, please remember that the model only trained phase 1 cannot generate the missing components (not in the reference characters). 
Occurring "KeyError" means that your reference characters are insufficient. In that case, phase 2 training can solve that issue.

**Comment by clscy** [comment]
Very thank you。
