### ISSUE TITLE
Question about p1dataset.py

### ISSUE THREAD

**Issue by yjunej** [clovaai/lffont#25]
**CombTestDataset class**

```
def __getitem__(self, index):
        font_name, trg_uni = self.fus[index]
        font_idx = self.fonts.index(font_name)

        style_unis, trg_comp_ids = self.sample_char(font_name, trg_uni)
        style_imgs = torch.stack([self.env_get(self.env, font_name, uni, self.transform) for uni in style_unis])

        font_idx = torch.LongTensor([font_idx])
        trg_dec_uni = torch.LongTensor([self.to_int(trg_uni)])

        content_img = self.env_get(self.env, self.content_font, trg_uni, self.transform)

        ret = (
            font_idx.repeat(len(trg_comp_ids)),
            torch.LongTensor(trg_comp_ids),
            style_imgs,
            font_idx,
            trg_comp_ids,
            trg_dec_uni,
            content_img
        )
```

I think return value doesn't contain the information of style_comp_ids, only trg_comp_ids 
Can I get an explanation about this?

Thank you.

**Comment by 8uos** [comment]
Hi.

The model is only available to generate the components in the style characters in phase 1 and so the style characters should contain all the components.
To satisfy this, we randomly picked a character that contains the component for each component of the target character. (please see the class function [sample_char](https://github.com/clovaai/lffont/blob/b8ebf28a716c9c1a7220d7c53fc063d7b09e5613/datasets/p1dataset.py#L178).)

In this case, extracting the remaining components of each style characters only wastes the memory; because they are not used for the generation.
So this code excludes the remaining components and only returns the target components.

**Comment by yjunej** [comment]
I get the picture. Thank you
