### ISSUE TITLE
Question about korean generator

### ISSUE THREAD

**Issue by work82mj** [clovaai/lffont#35]
In the paper, there are no details about korean generator; the number of sample fonts, and the number of seen/unseen characters.
I'm just curious about training details of korean.

**Comment by SanghyukChun** [comment]
The full detail is exactly the same as DM-Font
- https://github.com/clovaai/dmfont
- https://arxiv.org/abs/2005.10510
> Korean-handwriting and Thai-printing datasets were built from [UhBee fonts](http://uhbeefont.com/) and [Thai font collection](https://github.com/jeffmcneill/thai-font-collection), respectively. To ensure the style diversity of the dataset, one font was selected for each font family in our experiments.

We did not publish the full font files for training and evaluation in DM-Font, because font assets are usually not license-free. You can check the details in DM-Font repository and paper.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
